LOAD DATA 
CHARACTERSET  ZHS16GBK
INFILE '/mnt/hgfs/U/xmbus/txtdb/XMGJ_CARDTYPE.txt'
BADFILE 'bad_cardtype.bad' 
TRUNCATE INTO TABLE BUSGPS_XMGJ_CARDTYPE
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(
cardtypeid,
cardtypename
)
