LOAD DATA CHARACTERSET ZHS16GBK INFILE '/mnt/hgfs/U/xmbus/txtdb/tab_gpsbuslines.txt.temp'  BADFILE 'bad_BUSGPS_TAB_GPSBUSLINES.bad' TRUNCATE INTO TABLE BUSGPS_TAB_GPSBUSLINES FIELDS TERMINATEd BY "," 
TRAILING NULLCOLS 
(
FENZUMING,
XIANLUHAO,
CHEPAIHAO,
SHEBEIID,
SIMKAHAO
)
